image: docker:20.10.12

services:
  - docker:20.10.12-dind

before_script:
  - docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"

build-development:
  stage: build
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}":development-"${CI_COMMIT_SHORT_SHA} .
    - docker tag ${CI_REGISTRY_IMAGE}":development-"${CI_COMMIT_SHORT_SHA} ${CI_REGISTRY_IMAGE}":development-latest"